```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Liquor Sales in Iowa

This dataset https://data.iowa.gov/Sales-Distribution/2019-Iowa-Liquor-Sales/38x4-vs5h contains the spirits purchase information of Iowa Class “E” liquor licensees by product and date of purchase for 2019. The dataset can be used to analyze total spirits sales in Iowa of individual products at the store level.

**Submission instructions**: Create a folder named `ds202_hw5`, and name the RMarkDown file including your solutions `hw5.Rmd` under this folder. For the submission, create a GitHub repository named `ds202_hw5` under your GitHub account, and push both `hw5.Rmd` and the knitted `hw5.html` before the deadline. I will assume you use the same GitHub username as for your HW4 submission. The latest version of your homework appearing on GitHub before the deadline is graded. *It is crucial to follow the exact folder structure and file names*, so that your homework can be reproduced and graded by an automated script. This homework is **due on April 10** by 11:59 pm.

1. The complete dataset is too large. Download and import the alcohol sales data for Ames only: 

  a. Go to https://data.iowa.gov/Sales-Distribution/2019-Iowa-Liquor-Sales/38x4-vs5h
  b. Click Filter -- Filter -- Go advanced now
  c. Add a New Filter Condition: City is Ames.
  d. Export -- CSV -- Download
  e. Use `readr::read_csv` to import.
  
```{R}
library(lubridate)
library(dplyr)
library(stringr)
library(ggplot2)
library(tidyverse)
states <- map_data('state')

Liquor <- readr::read_csv('2019_Iowa_Liquor_Sales.csv')
```
  
2. Data cleaning: 
  a. extract geographic latitude and longitude from the variable `Store Location`
  b. make sure the variables are in the correct type, by converting incorrect variable types.
  c. extract year, month and day from the variable `Date` as separate columns.
  
```{R}
  pattern <- regex("POINT \\((-?\\d+.\\d+) (-?\\d+.\\d+)\\)")
  pointResult <- Liquor$`Store Location` %>%
    str_match(pattern)
  
  Liquor$longitude = as.numeric(pointResult[, 2])
  Liquor$latitude = as.numeric(pointResult[, 3])
  dates <- mdy(Liquor$Date)
  Liquor$Year <- year(dates)
  Liquor$Month <- month(dates)
  Liquor$Day <- day(dates)
```

  
3. First overview:
  a. Plot a scatterplot of lat and long of store locations. 
```{R}
  # In respect to Iowa
  states %>% filter(region == 'iowa') %>%
    ggplot(aes(x=long, y=lat)) + geom_path() +
    Liquor %>% geom_point(mapping=aes(x=longitude, y=latitude))

  # In respect to Ames
  Liquor %>%
    ggplot(aes(x=longitude, y=latitude)) + geom_point()
```
  
  b. Provide a visual breakdown of the liquor category (by `Category Name`). Include volume sold in the breakdown.
```{R}
  Liquor %>% count(`Category Name`) %>% arrange(desc(n)) %>% head(4) %>%
    ggplot(aes(x=`Category Name`, y=n)) + geom_bar(stat='identity') + ylab('Count') + ggtitle('2019 Ames Top Selling Liquor')
```
4. Find the daily sales liquor sales in Ames in 2019. Summarize the number of sales, volume of liquor sold, and amount of money spent.
```{R}
  summary <- Liquor %>% group_by(Date) %>% summarize(
    'Number of Sales'             = n(),
    'Volume of Liquor Sold (L)'   = sum(`Volume Sold (Liters)`),
    'Volume of Liquor Sold (Gal)' = sum(`Volume Sold (Gallons)`),
    'Money Spent'                 = sum(`Sale (Dollars)`),
  )

  summary
```
5. Plot volume sold by day (use a scatterplot of volume by day and facet by month). Discover trends with the help of `geom_smooth`. Describe any patterns.

```{R}
  summary$Date <- mdy(summary$Date)

  summary %>%
    ggplot(aes(x=day(Date), y=`Volume of Liquor Sold (L)`)) +
      geom_smooth() +
      facet_wrap(~ month(Date, abbr=FALSE, label=TRUE)) +
      xlab('Day') + ggtitle('Alcoholic Volume Sold in Ames, 2019')
```
6. Find the dates for ISU football home games in Fall 2019. Can you see a pattern? 

There appears to be home games on 8/31/19, 9/14/19, 9/21/19, 10/5/19, 10/26/19, 11/16/19, and 11/23/19. For our first instance of a home game, there appears to be a graduate increase in alcoholic volume sold preceeding the game at the end of August. Moving to September, there appears to be a slight increase in the middle of the month which quickly decreases towards the end of the month. In October, there a appears to be the same effect as in August with less of an intensity. This leads into November where we see a huge spike around the second to last game and a slight ramp at the end. It appears there is a clear association between fall football games and the sale of alcoholic volume where the largest difference occuring at the end of Auguest and the middle of November. These signify rather important events namely, the first and second to last football game. Though, I find it odd the last football game did not recieve as much attention as it's predecessor.


Note: your submission is supposed to be fully reproducible, i.e. the TA and I will 'knit' your submission in RStudio. 
